<?php

namespace AppBundle\Repository;

/**
 * OceanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OceanRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByLocale($locale = 'en')
    {
        //Make a Select query
        $qb = $this->createQueryBuilder('a');
        //$qb->select('a');
        //->orderBy(...) customize it

        // Use Translation Walker
        $query = $qb->getQuery();
        $query->setHint(
            \Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,
            'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
        );
        // Force the locale
        $query->setHint(
            \Gedmo\Translatable\TranslatableListener::HINT_TRANSLATABLE_LOCALE,
            $locale
        );
        return $query->getResult();
    }



}
